title: Lionel's quick GH tests
description: This is a test to see if this would be suitable for me
# Enable or disable the site search
search_enabled: true
#url: "https://sambuc.github.io/test-docs"
#show_downloads: true
#github:
#  zip_url: http://example.com/download.zip
#  another_url: another value
#theme: jekyll-theme-architect
remote_theme: pmarsceill/just-the-docs
