title: Lionel's quick GH tests
description: This is a test to see if this would be suitable for me

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
    "Just the Docs on GitHub":
      - "//github.com/pmarsceill/just-the-docs"

remote_theme: pmarsceill/just-the-docs
